version: '3'

volumes:
  shared:
    driver: local

services:
  workflow-hook:
    image:
      sagebionetworks/synapseworkflowhook
    volumes:
    - shared:/shared:rw
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - DOCKER_ENGINE_URL=${DOCKER_ENGINE_URL}
    - SYNAPSE_USERNAME=${SYNAPSE_USERNAME}
    - SYNAPSE_PASSWORD=${SYNAPSE_PASSWORD}
    - WORKFLOW_OUTPUT_ROOT_ENTITY_ID=${WORKFLOW_OUTPUT_ROOT_ENTITY_ID}
    - EVALUATION_TEMPLATES=${EVALUATION_TEMPLATES}
    - NOTIFICATION_PRINCIPAL_ID=${NOTIFICATION_PRINCIPAL_ID}
    - SHARE_RESULTS_IMMEDIATELY=${SHARE_RESULTS_IMMEDIATELY}
    - DATA_UNLOCK_SYNAPSE_PRINCIPAL_ID=${DATA_UNLOCK_SYNAPSE_PRINCIPAL_ID}
    - TOIL_CLI_OPTIONS=${TOIL_CLI_OPTIONS}
    - MAX_CONCURRENT_WORKFLOWS=${MAX_CONCURRENT_WORKFLOWS}
    - SUBMITTER_NOTIFICATION_MASK=${SUBMITTER_NOTIFICATION_MASK}
